Handle Send button error when no image is selected
Add additional check for NoneType in `image_from_url_text` to catch error caused by clicking "Send" buttons with no image currently selected in the gallery (``AttributeError: 'NoneType' object has no attribute 'startswith'``).