Fix AttributeError: 'ImageDraw' object has no attribute 'multiline_textsize' for Pillow >=10 when making grids.
Fixes AttributeError: 'ImageDraw' object has no attribute 'multiline_textsize' when using Pillow >10 trying to do X/Y/Z grids. This specially happens if using Python 3.12, where Pillow 10.1.0 is the least compatible version.

Draft for now, since stable is using Python 3.10. It can be applied either if updating the Pillow library version in the requirements or if using Python 3.12.