Update gradio
Fixed these errors:

```
python webui.py     --port 3000 --api --listen --xformers --enable-insecure-extension-access --ui-debug-mode     --ckpt-dir /workspace/sd-models --controlnet-dir /workspace/cn-models     --controlnet-annotator-models-path /workspace/cn-annotator
2023-07-26 02:16:14,830 - ControlNet - INFO - ControlNet v1.1.233
ControlNet preprocessor location: /workspace/cn-annotator
2023-07-26 02:16:14,963 - ControlNet - INFO - ControlNet v1.1.233
Running on local URL:  http://0.0.0.0:3000

To create a public link, set `share=True` in `launch()`.
Startup time: 8.0s (import torch: 2.7s, import gradio: 1.0s, setup paths: 1.2s, other imports: 0.5s, api.py: 0.5s, controlnet.py: 0.1s, lora_script.py: 0.1s, create ui: 0.7s, gradio launch: 0.8s).
Task exception was never retrieved
future: <Task finished name='e997xzzumt_319' coro=<Queue.process_events() done, defined at /usr/local/lib/python3.10/dist-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...ion_hash': 'e997xzzumt'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 159, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...ion_hash': 'e997xzzumt'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing
Task exception was never retrieved
future: <Task finished name='e997xzzumt_340' coro=<Queue.process_events() done, defined at /usr/local/lib/python3.10/dist-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...ion_hash': 'e997xzzumt'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 159, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...ion_hash': 'e997xzzumt'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing
```