Update code to work with Pydantic 2.0
It fixed these errors which were at the web ui launch:

```
root@8ca872a0f38f:/stable-diffusion-webui# python webui.py     --port 3000 --api --listen --xformers --enable-insecure-extension-access --ui-debug-mode     --ckpt-dir /workspace/sd-models --controlnet-dir /workspace/cn-models     --controlnet-annotator-models-path /workspace/cn-annotator
*** Error loading script: api.py
    Traceback (most recent call last):
      File "/stable-diffusion-webui/modules/scripts.py", line 295, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/api.py", line 8, in <module>
        from modules.api.models import *
      File "/stable-diffusion-webui/modules/api/models.py", line 112, in <module>
        ).generate_model()
      File "/stable-diffusion-webui/modules/api/models.py", line 97, in generate_model
        DynamicModel.__config__.allow_population_by_field_name = True
      File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_model_construction.py", line 205, in __getattr__
        raise AttributeError(item)
    AttributeError: __config__

---
*** Error loading script: batch_hijack.py
    Traceback (most recent call last):
      File "/stable-diffusion-webui/modules/scripts.py", line 295, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 7, in <module>
        from scripts import external_code
      File "/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *
      File "/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 9, in <module>
        from modules.api import api
      File "/stable-diffusion-webui/modules/api/api.py", line 19, in <module>
        from modules.api import models
      File "/stable-diffusion-webui/modules/api/models.py", line 112, in <module>
        ).generate_model()
      File "/stable-diffusion-webui/modules/api/models.py", line 97, in generate_model
        DynamicModel.__config__.allow_population_by_field_name = True
      File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_model_construction.py", line 205, in __getattr__
        raise AttributeError(item)
    AttributeError: __config__

---
*** Error loading script: controlnet.py
    Traceback (most recent call last):
      File "/stable-diffusion-webui/modules/scripts.py", line 295, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 13, in <module>
        from scripts import global_state, hook, external_code, processor, batch_hijack, controlnet_version, utils
      File "/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *
      File "/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 9, in <module>
        from modules.api import api
      File "/stable-diffusion-webui/modules/api/api.py", line 19, in <module>
        from modules.api import models
      File "/stable-diffusion-webui/modules/api/models.py", line 112, in <module>
        ).generate_model()
      File "/stable-diffusion-webui/modules/api/models.py", line 97, in generate_model
        DynamicModel.__config__.allow_population_by_field_name = True
      File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_model_construction.py", line 205, in __getattr__
        raise AttributeError(item)
    AttributeError: __config__

---
2023-07-26 02:19:07,342 - ControlNet - INFO - ControlNet v1.1.233
*** Error loading script: external_code.py
    Traceback (most recent call last):
      File "/stable-diffusion-webui/modules/scripts.py", line 295, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *
      File "/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 9, in <module>
        from modules.api import api
      File "/stable-diffusion-webui/modules/api/api.py", line 19, in <module>
        from modules.api import models
      File "/stable-diffusion-webui/modules/api/models.py", line 112, in <module>
        ).generate_model()
      File "/stable-diffusion-webui/modules/api/models.py", line 97, in generate_model
        DynamicModel.__config__.allow_population_by_field_name = True
      File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_model_construction.py", line 205, in __getattr__
        raise AttributeError(item)
    AttributeError: __config__

---
*** Error loading script: xyz_grid_support.py
    Traceback (most recent call last):
      File "/stable-diffusion-webui/modules/scripts.py", line 295, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/xyz_grid_support.py", line 8, in <module>
        from scripts.external_code import ResizeMode, ControlMode
      File "/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *
      File "/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 9, in <module>
        from modules.api import api
      File "/stable-diffusion-webui/modules/api/api.py", line 19, in <module>
        from modules.api import models
      File "/stable-diffusion-webui/modules/api/models.py", line 112, in <module>
        ).generate_model()
      File "/stable-diffusion-webui/modules/api/models.py", line 97, in generate_model
        DynamicModel.__config__.allow_population_by_field_name = True
      File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_model_construction.py", line 205, in __getattr__
        raise AttributeError(item)
    AttributeError: __config__

---
Traceback (most recent call last):
  File "/stable-diffusion-webui/webui.py", line 482, in <module>
    webui()
  File "/stable-diffusion-webui/webui.py", line 393, in webui
    shared.demo = modules.ui.create_ui()
  File "/stable-diffusion-webui/modules/ui.py", line 504, in create_ui
    modules.scripts.scripts_txt2img.setup_ui_for_section(category)
  File "/stable-diffusion-webui/modules/scripts.py", line 409, in setup_ui_for_section
    self.create_script_ui(script)
  File "/stable-diffusion-webui/modules/scripts.py", line 359, in create_script_ui
    import modules.api.models as api_models
  File "/stable-diffusion-webui/modules/api/models.py", line 112, in <module>
    ).generate_model()
  File "/stable-diffusion-webui/modules/api/models.py", line 97, in generate_model
    DynamicModel.__config__.allow_population_by_field_name = True
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_model_construction.py", line 205, in __getattr__
    raise AttributeError(item)
AttributeError: __config__
root@8ca872a0f38f:/stable-diffusion-webui#
```

It's required here: https://docs.pydantic.dev/latest/blog/pydantic-v2-alpha/#changes-to-config